#define CONFIG_ENABLE_UAF_CHECK 1
#define CONFIG_ENABLE_OOB_CHECK 1
#define CONFIG_ENABLE_OOB_OPTIMIZATION 1
#define CONFIG_ENABLE_REPORT 1
#define CONFIG_DISABLE_ESCAPE_STACK_LOC 1
#define CONFIG_ENABLE_ESCAPE_TYPE_ONLY 0