#!/bin/bash

set -e

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/../"

if [ $# -eq 0 ]
  then
    echo "USAGE: $0 [options] file..."
    exit 0
fi

source ${BASE}/src/safe_tcmalloc/.config

if [ "$ENABLE_GPROF" = "y" ] 
    then
	FLAGS="${BASE}/build/src/safe_tcmalloc/tcmalloc/static/libtcmalloc.a -g -pg -pthread"
    else 
	FLAGS="-L${BASE}/build/src/safe_tcmalloc/tcmalloc -ltcmalloc_tcmalloc"
fi

# The optimization level must be greater than -O0,
# otherwise some analysis methods cannot be enabled.
# But over-optimization (O2 or higher) can lead to changes in semantics.
exec clang++ -g -O1 -Xclang -load -Xclang ${BASE}/build/src/compiler_pass/libProtectionPass.so \
        "$@" \
        ${FLAGS} \
	    -Wl,-rpath,${BASE}/build/src/safe_tcmalloc/tcmalloc \
	    -Qunused-arguments \
        -Wpointer-arith -Wpointer-to-int-cast \
